### ISSUE TITLE
Can someone help me?

### ISSUE THREAD

**Issue by FungY911** [jetkai/openai-for-java#3]
[17:21:24 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ask' in plugin AIChat v1.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.19.3.jar:git-Paper-392]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-392]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-392]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-392]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-392]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-392]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-392]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-392]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-392]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-392]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at io.github.jetkai.openai.openai.OpenAIBuilderImpl.setApiKey(OpenAIBuilderImpl.java:135) ~[AIChatBot-1.0.0.jar:?]
        at io.github.jetkai.openai.openai.OpenAIBuilderImpl.setApiKey(OpenAIBuilderImpl.java:28) ~[AIChatBot-1.0.0.jar:?]
        at tech.codemein.aichat.commands.ASKCommand.exampleBuilders(ASKCommand.java:74) ~[AIChatBot-1.0.0.jar:?]
        at tech.codemein.aichat.commands.ASKCommand.onCommand(ASKCommand.java:42) ~[AIChatBot-1.0.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 23 more
        
        This is my code: (ignore the try)
![image](https://user-images.githubusercontent.com/74965749/224769989-c4ce8b46-fbab-4b8c-b34f-750012f2cd50.png)

**Comment by FungY911** [comment]
Im on Java 17

**Comment by jetkai** [comment]
@FungY911 Have you set the API key within your builder? The key must not be null.

**Comment by FungY911** [comment]
Yes, in config. 
![image](https://user-images.githubusercontent.com/74965749/224770895-376ebe33-2b22-4c16-8644-febdbb5c3065.png)

**Comment by FungY911** [comment]
There it is.
![image](https://user-images.githubusercontent.com/74965749/224771262-4d0e6ec7-51cf-4523-a8d3-f671da08e343.png)

**Comment by jetkai** [comment]
Using "System.getenv" will only get the environmental variables from your system.

You'll need to use `.setApiKey(FileManager.config.getString("openaiKey"));` to load it from a file.

Try hardcoding the API Key to make sure it works first.

The actual error is complaining that the API key is null:
![image](https://user-images.githubusercontent.com/26250917/224771742-b8fede5e-c6ba-4298-8d29-0d68e818d3ad.png)
